
# This is a basic workflow to help you get started with Actions

name: Run the bot

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron:  '30 10 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      # Runs a single command using the runners shell
      - name: install octokit
        run: bun add octokit
      - name: Run the script
        run: bun index.ts
        env:
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}} 
          USERS: ${{secrets.USERS}}
          DISCORDUSERS: ${{secrets.DISCORDUSERS}}
          PAT: ${{secrets.PAT}}
